### ISSUE TITLE
Move to Github Actions

### ISSUE THREAD

**Issue by jagot** [jagot/ThreadedSparseArrays.jl#6]

**Comment by rasmushenningsson** [comment]
Solved by #5 

Should we remove travis? (probably) and appveyor? (I see no reason to remove it).

**Comment by jagot** [comment]
Since with #5 Github Actions will run on all platforms, I don't think it necessary to run on AppVeyor too. I would just remove it.

**Comment by rasmushenningsson** [comment]
OK. I removed both.

**Comment by jagot** [comment]
Should remove the failing badge as well :) EDIT: and insert the Github Actions badge.

**Comment by rasmushenningsson** [comment]
Done.

But I think you need to fix the CodeCov setup since it's on your user. I'm not really sure what to do though.

**Comment by jagot** [comment]
What about it? I think it looks fine: https://codecov.io/gh/jagot/ThreadedSparseArrays.jl/tree/7da58624574289b24873e9ec611996859b2a9f60

I did turn off AppVeyor, which has to be done manually (for Travis, it's enough to delete `.travis.yml`).

**Comment by rasmushenningsson** [comment]
Ah perfect.
